import printer.(println);

instance Exception (Int);

// When the constructor throws the destructor should not be called

record Test (
    x: Int
);

overload Test(v, x) --> returned:Test{
    if (v)
        throw 1;
    returned.x = x;
} 

overload destroy(t:Test) {
    println("Destroyed ", t.x);
}

main() {
    try {
        var t = Test(false, 1);
        var t = Test(true, 0);
    }
    catch (e) {
        println("Caught");
    }
}
