record MyException(a: Int);

instance Exception (MyException);

main() {
    throw MyException(17);
}
