import printer.(println);

instance Exception (Int);

record Test (
    x: Int32
);

override destroy(t:Test) {
    println("Destroyed ", t.x);
}

m(x) {
    try {
        var r = Test(1);
        if (x == 1)
            throw 1;
        var r2 = Test(2);
    }
    catch (e) {
        println("Caught. Throwing again.");
        throw 2;
    }
    var r2 = Test(3);
}

main() {
    try {
        println("Hello World");
        m(0);
        var r = Test(20);
        m(1);
        var r = Test(30);
    }
    catch (e) {
        println("Caught");
    }
    return 0;
}
