import printer.(println);

instance Exception (Int);

record Test (
    x: Int32
);

Test() = Test(-1);

Test(x:Int32) --> returned:Test {
    println("Created ", x);
    returned.x = x;
}

Test(other:Test) --> returned:Test {
    println("Copied ", other.x);
    returned.x = other.x;
}

destroy(t:Test) {
    println("Destroyed ", t.x);
}

main () {
    try {
        var a = Test(1);
        if (true)
            throw 1;
        var b = Test(2);
    }
    catch (e) {
        println("Caught!");
    }
}
